output:
  format: tab

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen

linters-settings:
  dupl:
    threshold: 150
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 22
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0

linters:
  enable:
    - bodyclose
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - golint
    - gosec
    - lll
    - misspell
    - nakedret
    - stylecheck
    - unconvert
    - unparam
    - whitespace

  fast: false
